var hierarchy =
[
    [ "AutoGeneratedProgram", "class_auto_generated_program.html", null ],
    [ "Swapi.Core.UnitTests.Calculation.Strategy.BaseRangeCalculationStrategyTests", "class_swapi_1_1_core_1_1_unit_tests_1_1_calculation_1_1_strategy_1_1_base_range_calculation_strategy_tests.html", null ],
    [ "Swapi.Core.UnitTests.CalculationProducerTests", "class_swapi_1_1_core_1_1_unit_tests_1_1_calculation_producer_tests.html", null ],
    [ "Swapi.Core.UnitTests.Calculation.Strategy.ConcreteRangeCalculationStrategyTests", "class_swapi_1_1_core_1_1_unit_tests_1_1_calculation_1_1_strategy_1_1_concrete_range_calculation_strategy_tests.html", null ],
    [ "Exception", null, [
      [ "Swapi.Core.Calculation.CalculationException", "class_swapi_1_1_core_1_1_calculation_1_1_calculation_exception.html", null ]
    ] ],
    [ "IDisposable", null, [
      [ "Swapi.Core.DisposableSubscription< T >", "class_swapi_1_1_core_1_1_disposable_subscription.html", null ]
    ] ],
    [ "IObservable", null, [
      [ "Swapi.Core.CalculationProducer", "class_swapi_1_1_core_1_1_calculation_producer.html", null ]
    ] ],
    [ "IObserver", null, [
      [ "Swapi.Core.CalculationConsoleConsumer", "class_swapi_1_1_core_1_1_calculation_console_consumer.html", null ]
    ] ],
    [ "Swapi.Core.Calculation.IRangeCalculationStrategy", "interface_swapi_1_1_core_1_1_calculation_1_1_i_range_calculation_strategy.html", [
      [ "Swapi.Core.Calculation.Strategy.BaseRangeCalculationStrategy", "class_swapi_1_1_core_1_1_calculation_1_1_strategy_1_1_base_range_calculation_strategy.html", [
        [ "Swapi.Core.Calculation.Strategy.DailyRangeCalculationStrategy", "class_swapi_1_1_core_1_1_calculation_1_1_strategy_1_1_daily_range_calculation_strategy.html", null ],
        [ "Swapi.Core.Calculation.Strategy.MonthlyRangeCalculationStrategy", "class_swapi_1_1_core_1_1_calculation_1_1_strategy_1_1_monthly_range_calculation_strategy.html", null ],
        [ "Swapi.Core.Calculation.Strategy.NullRangeCalculationStrategy", "class_swapi_1_1_core_1_1_calculation_1_1_strategy_1_1_null_range_calculation_strategy.html", null ],
        [ "Swapi.Core.Calculation.Strategy.WeeklyRangeCalculationStrategy", "class_swapi_1_1_core_1_1_calculation_1_1_strategy_1_1_weekly_range_calculation_strategy.html", null ],
        [ "Swapi.Core.Calculation.Strategy.YearlyRangeCalculationStrategy", "class_swapi_1_1_core_1_1_calculation_1_1_strategy_1_1_yearly_range_calculation_strategy.html", null ]
      ] ]
    ] ],
    [ "Swapi.Core.Calculation.IRangeCalculationStrategyFactory", "interface_swapi_1_1_core_1_1_calculation_1_1_i_range_calculation_strategy_factory.html", [
      [ "Swapi.Core.Calculation.RangeCalculationStrategyFactory", "class_swapi_1_1_core_1_1_calculation_1_1_range_calculation_strategy_factory.html", null ]
    ] ],
    [ "Swapi.Core.Repository.IStarshipRepository", "interface_swapi_1_1_core_1_1_repository_1_1_i_starship_repository.html", [
      [ "Swapi.Core.Repository.StarshipWebApiRepository", "class_swapi_1_1_core_1_1_repository_1_1_starship_web_api_repository.html", null ]
    ] ],
    [ "Swapi.Core.Calculation.IStopsCalculator", "interface_swapi_1_1_core_1_1_calculation_1_1_i_stops_calculator.html", [
      [ "Swapi.Core.Calculation.StopsCalculator", "class_swapi_1_1_core_1_1_calculation_1_1_stops_calculator.html", null ]
    ] ],
    [ "JsonConverter", null, [
      [ "Swapi.Core.Model.Serialization.StarshipConvertor", "class_swapi_1_1_core_1_1_model_1_1_serialization_1_1_starship_convertor.html", null ]
    ] ],
    [ "Swapi.ResupplyStopCalculator.Program", "class_swapi_1_1_resupply_stop_calculator_1_1_program.html", null ],
    [ "Swapi.Core.UnitTests.Calculation.RangeCalculationStrategyFactoryTests", "class_swapi_1_1_core_1_1_unit_tests_1_1_calculation_1_1_range_calculation_strategy_factory_tests.html", null ],
    [ "Swapi.Core.Model.Starship", "class_swapi_1_1_core_1_1_model_1_1_starship.html", null ],
    [ "Swapi.Core.UnitTests.StarshipUtils", "class_swapi_1_1_core_1_1_unit_tests_1_1_starship_utils.html", null ],
    [ "Swapi.Core.Calculation.StopsCalculationResult", "class_swapi_1_1_core_1_1_calculation_1_1_stops_calculation_result.html", null ],
    [ "Swapi.Core.UnitTests.Calculation.Strategy.StopsCalculatorTests", "class_swapi_1_1_core_1_1_unit_tests_1_1_calculation_1_1_strategy_1_1_stops_calculator_tests.html", null ]
];